### ISSUE TITLE
有些字段看不懂

### ISSUE THREAD

**Issue by inceptiongt** [wibetter/json-schema-editor#19]
![image](https://user-images.githubusercontent.com/20478779/121041465-5d331880-c7e5-11eb-860b-8dd4f46dcebb.png)

如图，在线Demo中：
isRequire、format的一些值好像不是jsonschema标准里的字段。
这些是自定义的字段吗？

**Comment by wibetter** [comment]
isRequire、format是自定义字段，其中format主要用于标识字段展示类型（颗粒度更小的类型），format区别于type（type用于标识字段数值类型的）；isRequire用于表示此字段是否为必填字段。
