### ISSUE TITLE
安装直接报错

### ISSUE THREAD

**Issue by ranxin001** [wibetter/json-schema-editor#26]
npm install --save @wibtter/json-schema-editor

执行命令找不到该package

![image](https://user-images.githubusercontent.com/21697518/129198907-6b345110-f322-4e85-9ba9-f47b3a65790d.png)

**Comment by wibetter** [comment]
不好意思哈，使用说明文档中单词拼写错误（正确写法：@wibetter/json-schema-editor），请使用：npm install --save @wibetter/json-schema-editor安装使用。
